// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

namespace FintechTransactionSimulatorV2
{


    public partial class _Default
    {

        /// <summary>
    /// form1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private HtmlForm _form1;

        protected virtual HtmlForm form1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _form1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                _form1 = value;
            }
        }

        /// <summary>
    /// btnRefresh control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private Button _btnRefresh;

        protected virtual Button btnRefresh
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnRefresh;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                _btnRefresh = value;
            }
        }

        /// <summary>
    /// btnSimulate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private Button _btnSimulate;

        protected virtual Button btnSimulate
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnSimulate;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                _btnSimulate = value;
            }
        }

        /// <summary>
    /// lblBalance control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private Label _lblBalance;

        protected virtual Label lblBalance
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _lblBalance;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                _lblBalance = value;
            }
        }

        /// <summary>
    /// lblMessage control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private Label _lblMessage;

        protected virtual Label lblMessage
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _lblMessage;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                _lblMessage = value;
            }
        }

        /// <summary>
    /// gvTransactions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private GridView _gvTransactions;

        protected virtual GridView gvTransactions
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _gvTransactions;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                _gvTransactions = value;
            }
        }
    }
}